openapi: 3.0.3
info:
  title: Activity Search API
  description: API for searching activities based on various criteria.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /activity/search:
    get:
      summary: Search activities
      description: Retrieve a paginated list of activities based on search criteria.
      parameters:
        - in: query
          name: query
          schema:
            type: string
          description: Filter activities by title.
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            minimum: 1
          description: Page number (default is 1).
        - in: query
          name: size
          schema:
            type: integer
            default: 10
          description: Page size (default is 10).
      responses:
        '200':
          description: A paginated list of activities.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedResponseActivity'
components:
  schemas:
    Activity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        price:
          type: number
          format: float
        currency:
          type: string
        rating:
          type: number
          format: float
        specialOffer:
          type: boolean
        supplierName:
          type: string
        location:
          type: string
    PaginatedResponseActivity:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
        totalHits:
          type: integer
          format: int64
        totalPages:
          type: integer
        currentPage:
          type: integer
        pageSize:
          type: integer
        hasPrevious:
          type: boolean
        hasNext:
          type: boolean
